// https://www.figma.com/design/QlTWkQgrYB2zixN14oS0wv/Full-E-Commerce-Website-UI-UX-Design-(Community)?node-id=34-213&node-type=frame&t=7HSPy8XAWpGCkw4v-0
// this this the links of fogma design
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import Uppernavbar from "./components/uppernavbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}

      >
        <Uppernavbar />
        <Navbar /> {/*  navbar  */}
        {children}


      </body>
    </html>
  );
}
